# Generated by Django 6.0.2 on 2026-06-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contenttype',
            table='django_content_type',
        ),
    ]
