const LAST_UPDATED = '2026-03-06'

const SECTION = {
  borderTop: '1px solid #1a1a26',
  paddingTop: '2rem',
  marginBottom: '2.5rem',
} as const

const H2 = {
  fontSize: '1.05rem',
  fontWeight: 700,
  color: '#c8c8d8',
  marginBottom: '0.9rem',
  letterSpacing: '-0.01em',
} as const

const P = {
  color: '#888899',
  lineHeight: 1.75 as const,
  fontSize: '0.92rem',
  marginBottom: '0.75rem',
} as const

const UL = {
  color: '#888899',
  lineHeight: 1.75 as const,
  fontSize: '0.92rem',
  paddingLeft: '1.25rem',
  marginBottom: '0.75rem',
} as const

import SiteHeader from '../components/SiteHeader'
import { LanguageProvider, useLanguage } from '../contexts/LanguageContext'

function TermsHeader() {
  const { t } = useLanguage()
  return (
    <header style={{ marginBottom: '3rem' }}>
      <h1 style={{ fontSize: '1.9rem', fontWeight: 800, letterSpacing: '-0.02em', color: '#e8e8f0', marginBottom: '0.5rem' }}>
        {t.termsPageTitle}
      </h1>
      <p style={{ color: '#44445a', fontSize: '0.82rem' }}>{t.lastUpdated} {LAST_UPDATED}</p>
    </header>
  )
}

function TermsFooter() {
  const { t } = useLanguage()
  return (
    <footer style={{ borderTop: '1px solid #1a1a26', padding: '1.25rem 2rem', display: 'flex', gap: '1.25rem', flexWrap: 'wrap', fontSize: '0.78rem', color: '#44445a' }}>
      <a href="/terms" style={{ color: '#7c9ef8', textDecoration: 'none' }}>{t.termsLink}</a>
      <a href="/privacy" style={{ color: '#44445a', textDecoration: 'none' }}>{t.privacyLink}</a>
      <a href="/about" style={{ color: '#44445a', textDecoration: 'none' }}>{t.about}</a>
    </footer>
  )
}

export default function TermsPage() {
  return (
    <LanguageProvider>
    <div style={{ minHeight: '100vh', background: '#0f0f13', color: '#e0e0e0' }}>
      <title>Terms of Service — conflictradar.live</title>
      <meta name="description" content="Terms of Service and Disclaimer for conflictradar.live." />
      <link rel="canonical" href="https://conflictradar.live/terms" />

      <SiteHeader />

      <div style={{ maxWidth: 720, margin: '0 auto', padding: '3rem 2rem 5rem' }}>
        <TermsHeader />

        <section style={SECTION}>
          <h2 style={H2}>1. Acceptance of terms</h2>
          <p style={P}>
            By accessing or using conflictradar.live ("the Service"), you agree to be bound by these
            Terms of Service. If you do not agree, please do not use the Service.
          </p>
        </section>

        <section style={SECTION}>
          <h2 style={H2}>2. Description of service</h2>
          <p style={P}>
            conflictradar.live is a real-time event intelligence platform that aggregates, processes,
            and displays news and information sourced from publicly available third-party outlets,
            RSS feeds, and Telegram channels. The Service applies automated natural language processing
            to classify and geolocate events. It is provided free of charge for informational purposes only.
          </p>
        </section>

        <section style={SECTION}>
          <h2 style={H2}>3. Disclaimer — accuracy and reliability</h2>
          <p style={{ ...P, color: '#c8c8d8' }}>
            <strong>The information displayed on this Service is aggregated automatically from third-party
            sources and has not been independently verified.</strong>
          </p>
          <ul style={UL}>
            <li>Event classifications, locations, and sentiment scores are generated by automated NLP models and may be inaccurate, incomplete, or outdated.</li>
            <li>Geographic coordinates are approximate and may not reflect the exact location of an event.</li>
            <li>The absence of an event on the map does not mean the event did not occur.</li>
            <li>Source content belongs to the original publishers — we do not claim ownership of third-party articles.</li>
          </ul>
          <p style={P}>
            <strong style={{ color: '#e05252' }}>This Service must not be used as the sole or primary source
            of information for decisions involving personal safety, security operations, emergency response,
            military, medical, legal, or financial matters.</strong> Always verify critical information
            through official channels and qualified professionals.
          </p>
        </section>

        <section style={SECTION}>
          <h2 style={H2}>4. Limitation of liability</h2>
          <p style={P}>
            To the fullest extent permitted by applicable law, conflictradar.live and its operators
            shall not be liable for any direct, indirect, incidental, special, consequential, or
            punitive damages arising from your use of or inability to use the Service, including but
            not limited to damages resulting from:
          </p>
          <ul style={UL}>
            <li>Reliance on inaccurate, incomplete, or outdated information displayed on the Service</li>
            <li>Service interruptions, downtime, or data loss</li>
            <li>Errors in automated event classification or geolocation</li>
          </ul>
          <p style={P}>
            The Service is provided <strong style={{ color: '#c8c8d8' }}>"as is"</strong> and{' '}
            <strong style={{ color: '#c8c8d8' }}>"as available"</strong> without warranties of any kind,
            express or implied, including warranties of merchantability, fitness for a particular purpose,
            or non-infringement.
          </p>
        </section>

        <section style={SECTION}>
          <h2 style={H2}>5. Intellectual property</h2>
          <p style={P}>
            Article titles, summaries, and content displayed on the Service are sourced from and remain
            the property of their original publishers. conflictradar.live claims no copyright over
            third-party content. The underlying software, maps, and original visual design of the
            Service are the property of conflictradar.live.
          </p>
          <p style={P}>
            If you believe your copyrighted content is being displayed in a manner that infringes your
            rights, please contact us at{' '}
            <a href="mailto:contact@conflictradar.live" style={{ color: '#7c9ef8' }}>contact@conflictradar.live</a>.
          </p>
        </section>

        <section style={SECTION}>
          <h2 style={H2}>6. Acceptable use</h2>
          <p style={P}>You agree not to:</p>
          <ul style={UL}>
            <li>Scrape or systematically download data from the Service at scale without prior written permission</li>
            <li>Use the Service for any unlawful purpose or in violation of any applicable regulation</li>
            <li>Attempt to disrupt, overload, or circumvent the security of the Service</li>
            <li>Misrepresent the accuracy or origin of data sourced from the Service</li>
          </ul>
        </section>

        <section style={SECTION}>
          <h2 style={H2}>7. External links and sources</h2>
          <p style={P}>
            The Service links to and aggregates content from external websites over which we have no
            control. We are not responsible for the content, accuracy, or privacy practices of those
            third-party sites. Links to external sites do not constitute endorsement.
          </p>
        </section>

        <section style={{ ...SECTION, marginBottom: 0 }}>
          <h2 style={H2}>8. Changes to these terms</h2>
          <p style={{ ...P, marginBottom: 0 }}>
            We reserve the right to update these Terms of Service at any time. The "Last updated" date
            reflects the most recent revision. Continued use of the Service after changes are posted
            constitutes acceptance of the revised terms. For questions, contact{' '}
            <a href="mailto:contact@conflictradar.live" style={{ color: '#7c9ef8' }}>contact@conflictradar.live</a>.
          </p>
        </section>
      </div>

      <TermsFooter />
    </div>
    </LanguageProvider>
  )
}

export const getConfig = async () => ({ render: 'static' as const })
