# Generated by Django 6.0.2 on 2026-06-10 21:29

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='forecast',
            new_name='core_foreca_symbol_10ab5f_idx',
            old_name='core_forecast_symbol_gen_idx',
        ),
        migrations.RenameIndex(
            model_name='forecast',
            new_name='core_foreca_stream__1c3b6f_idx',
            old_name='core_forecast_stream_key_idx',
        ),
        migrations.RenameIndex(
            model_name='forecast',
            new_name='core_foreca_generat_1afbef_idx',
            old_name='core_forecast_generated_at_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='core_topic_is_curr_ff956c_idx',
            old_name='core_topic_is_current_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='core_topic_is_acti_37701b_idx',
            old_name='core_currenttopic_active_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='core_topic_categor_6a12b8_idx',
            old_name='core_currenttopic_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='core_topic_started_1764c0_idx',
            old_name='core_currenttopic_started_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='core_topic_ended_a_d6c923_idx',
            old_name='core_currenttopic_ended_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='core_topic_parent__0f1fb8_idx',
            old_name='core_currenttopic_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='core_topic_histori_bcdeea_idx',
            old_name='core_topic_hist_month_day_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='topics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='When this topic resolved or faded. Null means still ongoing.', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Admin override: always shown in header, never auto-demoted.'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_top_level',
            field=models.BooleanField(default=False, help_text='Auto-set: shown in UI header when score passes threshold.'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When this topic first appeared in the news', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_score',
            field=models.FloatField(default=0.0, help_text='Composite ranking score, updated by tag_topics_task.'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_top_level'], name='core_topic_is_top__f4d612_idx'),
        ),
    ]
